#!/bin/bash
gulp build
echo "Deploy.."
cd dist
git init
git remote add origin git@github.com:portokallidis/portokallidis.github.com.git
git add .
git commit -am"deploy"
git push -f origin master
cd ..
